add deploy-infrastructure job

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -17,7 +17,10 @@ commands:
           when: << parameters.when_to_run >> 
           command: |
             aws cloudformation delete-stack \
-              --stack-name prod-${CIRCLE_WORKFLOW_ID}
+              --stack-name udapeople-frontend-${CIRCLE_WORKFLOW_ID}
+            aws cloudformation delete-stack \
+              --stack-name udapeople-backend-${CIRCLE_WORKFLOW_ID}
+            aws s3 rm --recursive  s3://udapeople-${CIRCLE_WORKFLOW_ID}
 
 
   revert-migrations:
@@ -46,8 +49,8 @@ jobs:
     steps:
       - slack/notify:
           event: fail 
-          template: basic_fail_1 
-          channel: '#devOps' 
+          template: basic_fail_1
+          channel: '#devOps'
 
   build-frontend:
     docker:
@@ -91,11 +94,11 @@ jobs:
       - restore_cache:
           keys: [frontend-build]
       - run:
-          name: test front-end 
+          name: test front-end
           command: |
-           cd frontend 
+           cd frontend
            npm install
-           npm run test 
+           npm run test
 
   test-backend:
     docker:
@@ -105,17 +108,17 @@ jobs:
       - restore_cache:
           keys: [backend-build]
       - run:
-          name: test backend-end 
+          name: test backend-end
           command: |
            cd backend
            npm install
-           npm run test 
+           npm run test
       - run:
           name: e2e test backend-end 
           command: |
            cd backend
            npm install
-           npm run test 
+           npm run test
             
   scan-frontend:
     docker:
@@ -125,9 +128,9 @@ jobs:
       - restore_cache:
           keys: [Frontend-build]
       - run:
-          name: scan front-end 
+          name: scan front-end
           command: |
-           cd frontend 
+           cd frontend
            npm audit fix --audit-level=critical --force
 
   scan-backend:
@@ -138,180 +141,192 @@ jobs:
       - restore_cache:
           keys: [backend-build]
       - run:
-          name: scan front-end 
+          name: scan front-end
           command: |
            cd backend
            npm audit fix --audit-level=critical --force
       - slack/notify:
-          channel: C022RQRDUNP 
+          channel: C022RQRDUNP
           event: fail
           template: basic_fail_1
 
-          #  deploy-infrastructure:
-          #    docker:
-          #      # Docker image here that supports AWS CLI
-          #    steps:
-          #      # Checkout code from git
-          #      - run:
-          #          name: Ensure back-end infrastructure exists
-          #          command: |
-          #            aws cloudformation deploy \
-          #              --template-file .circleci/files/backend.yml \
-          #              #--tags project=your-tag \
-          #              # --stack-name "your back-end stack name with workflow id" \
-          #              # --parameter-overrides ID="your workflow id"  
-          #              exit 1
-          #      - run:
-          #          name: Ensure front-end infrastructure exist
-          #          command: |
-          #            aws cloudformation deploy \
-          #              --template-file .circleci/files/frontend.yml \
-          #              #--tags project=your-tag \
-          #              # --stack-name "your front-end stack name with workflow id" \
-          #              # --parameter-overrides ID="your workflow id"  
-          #              exit 1
-          #      - run:
-          #          name: Add back-end ip to ansible inventory
-          #          command: |
-          #            # Your code here
-          #            exit 1
-          #      - persist_to_workspace:
-          #          root: ~/
-          #          paths:
-          #            - project/.circleci/ansible/inventory.txt
-          #      # Here's where you will add some code to rollback on failure      
-          #
-          #  configure-infrastructure:
-          #    docker:
-          #      # Docker image here that supports Ansible
-          #    steps:
-          #      # Checkout code from git
-          #      # Add ssh keys with fingerprint
-          #      # attach workspace
-          #      - run:
-          #          name: Install dependencies
-          #          command: |
-          #            # Your code here
-          #            exit 1
-          #      - run:
-          #          name: Configure server
-          #          command: |
-          #            # Your code here
-          #            exit 1
-          #      # Here's where you will add some code to rollback on failure      
-          #
-          #  run-migrations:
-          #    docker:
-          #      # Docker image here that supports NodeJS
-          #    steps:
-          #      # Checkout code from git
-          #      - run:
-          #          name: Run migrations
-          #          command: |
-          #            # Your code here
-          #            exit 1
-          #      - run:
-          #          name: Send migration results to memstash
-          #          command: |
-          #            # Your code here
-          #            exit 1
-          #     # Here's where you will add some code to rollback on failure      
-          #
-          #  deploy-frontend:
-          #    docker:
-          #      # Docker image here that supports AWS CLI
-          #    steps:
-          #      # Checkout code from git
-          #      - run:
-          #          name: Install dependencies
-          #          command: |
-          #            # your code here
-          #      - run:
-          #          name: Get backend url
-          #          command: |
-          #            # your code here
-          #            export API_URL="http://${BACKEND_IP}:3030"
-          #            echo "${API_URL}"
-          #      - run:
-          #          name: Deploy frontend objects
-          #          command: |
-          #            # your code here
-          #      # Here's where you will add some code to rollback on failure      
-          #                    
-          #  deploy-backend:
-          #    docker:
-          #      # Docker image here that supports Ansible
-          #    steps:
-          #      # Checkout code from git
-          #      # Add ssh keys with fingerprint
-          #      # attach workspace
-          #      - run:
-          #          name: Install dependencies
-          #          command: |
-          #            # your code here
-          #      - run:
-          #          name: Deploy backend
-          #          command: |
-          #            # your code here
-          #      # Here's where you will add some code to rollback on failure  
-          #
-          #  smoke-test:
-          #    docker:
-          #      # Lightweight Docker image 
-          #    steps:
-          #      # Checkout code from git
-          #      - run:
-          #          name: Install dependencies
-          #          command: |
-          #            # your code here
-          #      - run:
-          #          name: Get backend url
-          #          command: |
-          #            # your code here
-          #      - run:
-          #          name: Backend smoke test.
-          #          command: |
-          #            # your code here
-          #      - run:
-          #          name: Frontend smoke test.
-          #          command: |
-          #            # your code here
-          #      # Here's where you will add some code to rollback on failure  
-          #
-          #  cloudfront-update:
-          #    docker:
-          #      # Docker image here that supports AWS CLI
-          #    steps:
-          #      # Checkout code from git
-          #      - run:
-          #          name: Install dependencies
-          #          command: |
-          #            # your code here
-          #      - run:
-          #          name: Update cloudfront distribution
-          #          command: |
-          #            # your code here
-          #      # Here's where you will add some code to rollback on failure  
-          #
-          #cleanup:
-          #    docker:
-          #      # Docker image here
-          #    steps:
-          #      # Checkout code from git
-          #      - run:
-          #          name: Get old stack workflow id
-          #          command: |
-          #            # your code here
-          #            export OldWorkflowID="the id here"
-          #            export STACKS=[] #put the list of stacks here
-          #      - run:
-          #          name: Remove old stacks and files
-          #          command: |
-          #            if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
-          #            then
-          #              # your code here
-          #            fi
-          #            
+  deploy-infrastructure:
+    docker:
+      - image: amazon/aws-cli
+    steps:
+      - checkout
+      - run: yum -y install tar gzip 
+      - run:
+          name: Ensure back-end infrastructure exists
+          command: |
+            aws cloudformation deploy \
+              --template-file .circleci/files/backend.yml \
+              --tags project=udapeople-backend-${CIRCLE_WORKFLOW_ID} \
+              --stack-name prod-${CIRCLE_WORKFLOW_ID} \
+              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID}"  
+              #exit 1
+      - run:
+          name: Ensure front-end infrastructure exist
+          command: |
+              aws cloudformation deploy \
+                --template-file .circleci/files/frontend.yml \
+                --tags project=udapeople-frontend-${CIRCLE_WORKFLOW_ID} \
+                --stack-name prod-${CIRCLE_WORKFLOW_ID} \
+                --parameter-overrides ID="${CIRCLE_WORKFLOW_ID}"
+                #exit 1
+      - run:
+          name: Add back-end ip to ansible inventory
+          command: |
+             INSTSNCE_IP=$(aws ec2 describe-instances \
+             --filters "Name=tag:Name,Value:backend-${CIRCLE_WORKFLOW_ID}" \
+             --query "Reservations[*].instances[*].PublicIpAdress" \
+             --output text>>./.circleci/ansible.inventory.txt)
+
+               echo ${INSTSNCE_IP} >> ./.circleci/ansible/inventory.txt
+               echo INSTSNCE_IP ${INSTSNCE_IP}
+               curl -H "Content-Type: text/plain" -H "token: ac7bae0c-4466-4e1d-8e7c-47338a852c5f" \
+               --request PUT \
+               --data "$INSTANCE_IP" https://api.memstash.io/values/INSTANCE_IP
+               #exit 1
+      - persist_to_workspace:
+          root: ~/
+          paths:
+            - project/.circleci/ansible/inventory.txt
+      - destroy-environment
+
+      # Here's where you will add some code to rollback on failure      
+  
+        #  configure-infrastructure:
+        #    docker:
+        #      # Docker image here that supports Ansible
+        #    steps:
+        #      # Checkout code from git
+        #      # Add ssh keys with fingerprint
+        #      # attach workspace
+        #      - run:
+        #          name: Install dependencies
+        #          command: |
+        #            # Your code here
+        #            exit 1
+        #      - run:
+        #          name: Configure server
+        #          command: |
+        #            # Your code here
+        #            exit 1
+        #      # Here's where you will add some code to rollback on failure      
+        #
+        #  run-migrations:
+        #    docker:
+        #      # Docker image here that supports NodeJS
+        #    steps:
+        #      # Checkout code from git
+        #      - run:
+        #          name: Run migrations
+        #          command: |
+        #            # Your code here
+        #            exit 1
+        #      - run:
+        #          name: Send migration results to memstash
+        #          command: |
+        #            # Your code here
+        #            exit 1
+        #     # Here's where you will add some code to rollback on failure      
+        #
+        #  deploy-frontend:
+        #    docker:
+        #      # Docker image here that supports AWS CLI
+        #    steps:
+        #      # Checkout code from git
+        #      - run:
+        #          name: Install dependencies
+        #          command: |
+        #            # your code here
+        #      - run:
+        #          name: Get backend url
+        #          command: |
+        #            # your code here
+        #            export API_URL="http://${BACKEND_IP}:3030"
+        #            echo "${API_URL}"
+        #      - run:
+        #          name: Deploy frontend objects
+        #          command: |
+        #            # your code here
+        #      # Here's where you will add some code to rollback on failure      
+        #                    
+        #  deploy-backend:
+        #    docker:
+        #      # Docker image here that supports Ansible
+        #    steps:
+        #      # Checkout code from git
+        #      # Add ssh keys with fingerprint
+        #      # attach workspace
+        #      - run:
+        #          name: Install dependencies
+        #          command: |
+        #            # your code here
+        #      - run:
+        #          name: Deploy backend
+        #          command: |
+        #            # your code here
+        #      # Here's where you will add some code to rollback on failure  
+        #
+        #  smoke-test:
+        #    docker:
+        #      # Lightweight Docker image 
+        #    steps:
+        #      # Checkout code from git
+        #      - run:
+        #          name: Install dependencies
+        #          command: |
+        #            # your code here
+        #      - run:
+        #          name: Get backend url
+        #          command: |
+        #            # your code here
+        #      - run:
+        #          name: Backend smoke test.
+        #          command: |
+        #            # your code here
+        #      - run:
+        #          name: Frontend smoke test.
+        #          command: |
+        #            # your code here
+        #      # Here's where you will add some code to rollback on failure  
+        #
+        #  cloudfront-update:
+        #    docker:
+        #      # Docker image here that supports AWS CLI
+        #    steps:
+        #      # Checkout code from git
+        #      - run:
+        #          name: Install dependencies
+        #          command: |
+        #            # your code here
+        #      - run:
+        #          name: Update cloudfront distribution
+        #          command: |
+        #            # your code here
+        #      # Here's where you will add some code to rollback on failure  
+        #
+        #cleanup:
+        #    docker:
+        #      # Docker image here
+        #    steps:
+        #      # Checkout code from git
+        #      - run:
+        #          name: Get old stack workflow id
+        #          command: |
+        #            # your code here
+        #            export OldWorkflowID="the id here"
+        #            export STACKS=[] #put the list of stacks here
+        #      - run:
+        #          name: Remove old stacks and files
+        #          command: |
+        #            if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
+        #            then
+        #              # your code here
+        #            fi
+        #            
 
 workflows:
   default:
@@ -328,11 +343,12 @@ workflows:
            requires: [build-frontend]
        - notify:
            context: slack-secrets
-    #   - deploy-infrastructure:
-    #       requires: [test-frontend, test-backend, scan-frontend, scan-backend]
-    #       filters:
-    #         branches:
-    #           only: [test-feature-branch]
+       - deploy-infrastructure:
+           requires: [test-frontend, test-backend, scan-frontend, scan-backend]
+           filters:
+             branches:
+               only: [master]
+               #only: [test-feature-branch]
     #   - configure-infrastructure:
     #       requires: [deploy-infrastructure]
     #   - run-migrations:
