add run-migrations job

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -153,14 +153,14 @@ jobs:
       - image: amazon/aws-cli
     steps:
       - checkout
-      - run: yum -y install tar gzip 
+      - run: yum -y install tar gzip jq npm
       - run:
           name: Ensure back-end infrastructure exists
           command: |
             aws cloudformation deploy \
               --template-file .circleci/files/backend.yml \
               --tags project=udapeople-backend-${CIRCLE_WORKFLOW_ID} \
-              --stack-name prod-${CIRCLE_WORKFLOW_ID} \
+              --stack-name udapeople-backend-${CIRCLE_WORKFLOW_ID} \
               --parameter-overrides ID="${CIRCLE_WORKFLOW_ID}"  
               #exit 1
       - run:
@@ -169,27 +169,31 @@ jobs:
               aws cloudformation deploy \
                 --template-file .circleci/files/frontend.yml \
                 --tags project=udapeople-frontend-${CIRCLE_WORKFLOW_ID} \
-                --stack-name prod-${CIRCLE_WORKFLOW_ID} \
+                --stack-name udapeople-frontend-${CIRCLE_WORKFLOW_ID} \
                 --parameter-overrides ID="${CIRCLE_WORKFLOW_ID}"
                 #exit 1
       - run:
           name: Add back-end ip to ansible inventory
           command: |
-             INSTSNCE_IP=$(aws ec2 describe-instances \
+             echo "[web]" > .circleci/ansible/inventory.txt
+             INSTANCE_IP=$(aws ec2 describe-instances \
              --filters Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID} \
-             --query "Reservations[*].Instances[*].PublicIpAdress" \
-             --output text >>./.circleci/ansible.inventory.txt)
+             --query 'Reservations[*].Instances[*].PublicIpAddress' \
+             --output text >> ./.circleci/ansible/inventory.txt)
 
-               echo ${INSTSNCE_IP} >> ./.circleci/ansible/inventory.txt
-               echo INSTSNCE_IP ${INSTSNCE_IP}
-               curl -H "Content-Type: text/plain" -H "token: ac7bae0c-4466-4e1d-8e7c-47338a852c5f" \
-               --request PUT \
-               --data "$INSTANCE_IP" https://api.memstash.io/values/INSTANCE_IP
-               #exit 1
+              echo ${INSTANCE_IP} >> ./.circleci/ansible/inventory.txt
+              echo INSTANCE_IP ${INSTANCE_IP}
+
+              cat ./.circleci/ansible/inventory.txt
+
+              curl -H "Content-Type: text/plain" -H "token: ac7bae0c-4466-4e1d-8e7c-47338a852c5f" \
+              --request PUT \
+              --data "$INSTANCE_IP" https://api.memstash.io/values/INSTANCE_IP
+              #exit 1
       - persist_to_workspace:
-          root: ~/
+          root: .circleci/ansible
           paths:
-            - project/.circleci/ansible/inventory.txt
+            - inventory.txt
       - destroy-environment
 
   
@@ -200,7 +204,7 @@ jobs:
     steps:
       - checkout
       - add_ssh_keys:
-          fingerprints: ['7f:b0:56:93:84:62:8f:47:4d:82:dd:ae:7a:86:85:2d']
+          fingerprints: ['7f:b0:56:93:84:62:8f:47:4d:82:dd:ae:7a:86:85:2d'] #['e9:17:e0:16:aa:a7:e1:98:39:35:5c:43:ca:3e:3f:99'] 
 
       - attach_workspace:
             at: ./.circleci/ansible 
@@ -215,131 +219,158 @@ jobs:
             apk add --update py3-pip
             apk add --update tar
             pip3 install awscli
+            # - run:
+            #     name: verify ansible hosts
+            #     command: |
+            #       ansible all --list-hosts
 
       - run:
            name: Configure server
            working_directory: ./.circleci/ansible 
            command: |
-             ansible-playbook -i inventory main.yml
-
+             echo PWD $(pwd)
+             ansible-playbook -i inventory.txt configure-server.yml
              #exit 1
       - destroy-environment
-      
-
-          # Here's where you will add some code to rollback on failure      
   
-        #  run-migrations:
-        #    docker:
-        #      # Docker image here that supports NodeJS
-        #    steps:
-        #      # Checkout code from git
-        #      - run:
-        #          name: Run migrations
-        #          command: |
-        #            # Your code here
-        #            exit 1
-        #      - run:
-        #          name: Send migration results to memstash
-        #          command: |
-        #            # Your code here
-        #            exit 1
-        #     # Here's where you will add some code to rollback on failure      
-        #
-        #  deploy-frontend:
-        #    docker:
-        #      # Docker image here that supports AWS CLI
-        #    steps:
-        #      # Checkout code from git
-        #      - run:
-        #          name: Install dependencies
-        #          command: |
-        #            # your code here
-        #      - run:
-        #          name: Get backend url
-        #          command: |
-        #            # your code here
-        #            export API_URL="http://${BACKEND_IP}:3030"
-        #            echo "${API_URL}"
-        #      - run:
-        #          name: Deploy frontend objects
-        #          command: |
-        #            # your code here
-        #      # Here's where you will add some code to rollback on failure      
-        #                    
-        #  deploy-backend:
-        #    docker:
-        #      # Docker image here that supports Ansible
-        #    steps:
-        #      # Checkout code from git
-        #      # Add ssh keys with fingerprint
-        #      # attach workspace
-        #      - run:
-        #          name: Install dependencies
-        #          command: |
-        #            # your code here
-        #      - run:
-        #          name: Deploy backend
-        #          command: |
-        #            # your code here
-        #      # Here's where you will add some code to rollback on failure  
-        #
-        #  smoke-test:
-        #    docker:
-        #      # Lightweight Docker image 
-        #    steps:
-        #      # Checkout code from git
-        #      - run:
-        #          name: Install dependencies
-        #          command: |
-        #            # your code here
-        #      - run:
-        #          name: Get backend url
-        #          command: |
-        #            # your code here
-        #      - run:
-        #          name: Backend smoke test.
-        #          command: |
-        #            # your code here
-        #      - run:
-        #          name: Frontend smoke test.
-        #          command: |
-        #            # your code here
-        #      # Here's where you will add some code to rollback on failure  
-        #
-        #  cloudfront-update:
-        #    docker:
-        #      # Docker image here that supports AWS CLI
-        #    steps:
-        #      # Checkout code from git
-        #      - run:
-        #          name: Install dependencies
-        #          command: |
-        #            # your code here
-        #      - run:
-        #          name: Update cloudfront distribution
-        #          command: |
-        #            # your code here
-        #      # Here's where you will add some code to rollback on failure  
-        #
-        #cleanup:
-        #    docker:
-        #      # Docker image here
-        #    steps:
-        #      # Checkout code from git
-        #      - run:
-        #          name: Get old stack workflow id
-        #          command: |
-        #            # your code here
-        #            export OldWorkflowID="the id here"
-        #            export STACKS=[] #put the list of stacks here
-        #      - run:
-        #          name: Remove old stacks and files
-        #          command: |
-        #            if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
-        #            then
-        #              # your code here
-        #            fi
-        #            
+  run-migrations:
+    docker:
+      - image: circleci/node:13.8.0
+    steps:
+      - checkout
+      - run:
+          name: Run migrations
+          command: |
+            cd backend
+            npm audit fix --force
+            npm install
+            touch migrations.txt
+            npm run migrations >> migrations.txt
+            cat migration.txt 
+            #exit 1
+      - run:
+          name: Send migration results to memstash
+          command: |
+            if grep "has been executed successfully" migrations.txt
+            then
+            curl -H "Content-Type: text/plain" -H "token: ac7bae0c-4466-4e1d-8e7c-47338a852c5f" \
+            --request PUT \
+            --data "1" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID}
+            else
+            curl -H "Content-Type: text/plain" -H "token: ac7bae0c-4466-4e1d-8e7c-47338a852c5f" \
+            --request PUT \
+            --data "0" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID}
+            fi
+      - revert-migrations
+
+      # exit 1
+      #
+      # deploy-frontend:
+      #   docker:
+      #     - image: amazon/aws-cli
+      #   steps:
+      #     - checkout # Checkout code from git
+      #     - run:
+      #         name: Install dependencies
+      #         command: |
+      #           yum -y install tar gzip 
+      #           curl -sL https://rpm.nodesource.com/setup_lts.x | bash -
+      #           yum -y install nodejs
+      #     - run:
+      #         name: Get backend url
+      #         command: |
+      #           BACKEND_IP=$(curl -H "token: ${CIRCLE_WORKFLOW_ID}" \
+      #             --request GET https://api.memstash.io/values/BACKEND_IP)
+
+      #           export API_URL="http://${BACKEND_IP}:3030"
+      #           echo "${API_URL}"
+
+      #           cd frontend
+      #           npm install
+      #           npm run build
+      #     - run:
+      #         name: Deploy frontend objects
+      #         command: |
+      #           aws s3 cp .frontend/dist s3://udapeople-${CIRCLE_WORKFLOW_ID}/ --recursive
+
+      #     - destroy-environment
+      # your code here
+      #Here's where you will add some code to rollback on failure      
+      #                    
+      #  deploy-backend:
+      #    docker:
+      #      # Docker image here that supports Ansible
+      #    steps:
+      #      # Checkout code from git
+      #      # Add ssh keys with fingerprint
+      #      # attach workspace
+      #      - run:
+      #          name: Install dependencies
+      #          command: |
+      #            # your code here
+      #      - run:
+      #          name: Deploy backend
+      #          command: |
+      #            # your code here
+      #      # Here's where you will add some code to rollback on failure  
+      #
+      #  smoke-test:
+      #    docker:
+      #      # Lightweight Docker image 
+      #    steps:
+      #      # Checkout code from git
+      #      - run:
+      #          name: Install dependencies
+      #          command: |
+      #            # your code here
+      #      - run:
+      #          name: Get backend url
+      #          command: |
+      #            # your code here
+      #      - run:
+      #          name: Backend smoke test.
+      #          command: |
+      #            # your code here
+      #      - run:
+      #          name: Frontend smoke test.
+      #          command: |
+      #            # your code here
+      #      # Here's where you will add some code to rollback on failure  
+      #
+      #  cloudfront-update:
+      #    docker:
+      #      # Docker image here that supports AWS CLI
+      #    steps:
+      #      # Checkout code from git
+      #      - run:
+      #          name: Install dependencies
+      #          command: |
+      #            # your code here
+      #      - run:
+      #          name: Update cloudfront distribution
+      #          command: |
+      #            # your code here
+      #      # Here's where you will add some code to rollback on failure  
+      #
+      #cleanup:
+      #    docker:
+      #      # Docker image here
+      #    steps:
+      #      # Checkout code from git
+      #      - run:
+      #          name: Get old stack workflow id
+      #          command: |
+      #            # your code here
+      #            export OldWorkflowID="the id here"
+      #            export STACKS=[] #put the list of stacks here
+      #      - run:
+      #          name: Remove old stacks and files
+      #          command: |
+      #            if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
+      #            then
+      #              # your code here
+      #            fi
+      #            
 
 workflows:
   default:
@@ -362,10 +393,10 @@ workflows:
              branches:
                only: [master]
                #only: [test-feature-branch]
-    #   - configure-infrastructure:
-    #       requires: [deploy-infrastructure]
-    #   - run-migrations:
-    #       requires: [configure-infrastructure]
+       - configure-infrastructure:
+           requires: [deploy-infrastructure]
+       - run-migrations:
+           requires: [configure-infrastructure]
     #   - deploy-frontend:
     #       requires: [run-migrations]
     #   - deploy-backend:
